import {
  BsBell,
  BsSearch,
  BsX,
  BsChevronRight,
  BsFacebook,
  BsTwitter,
  BsYoutube,
  BsInstagram,
  BsLinkedin,
  BsTelephone,
  BsFillExclamationCircleFill,
  BsChevronLeft,
  BsStar,
  BsPerson,
  BsReplyFill,
  BsHouseDoor,
  BsList,
  BsCashCoin,
  BsPrinter,
  BsGearWideConnected,
  BsEmojiLaughing,
  BsCloudDrizzle,
  BsLightbulb,
  BsFront,
  BsEnvelope,
  BsPlusCircleDotted,
  BsArrowDownCircle,
  BsImages,
  BsImageAlt,
  BsChatRightDots,
  BsCalendarEvent,
  BsCalendarCheck,
  BsFilter,
  BsMenuButtonWideFill,
  BsFileText,
  BsListCheck,
  BsSortUp,
  BsNewspaper,
  BsPersonVideo2,
  BsLink45Deg,
  BsLayoutSplit,
  BsFileEarmarkMedical,
  BsDownload,
  BsCheck,
  BsEye,
  BsChevronDoubleDown,
  BsCreditCard2Front,
  BsShieldLock,
  BsFingerprint,
  BsPeopleFill,
  BsStarFill,
  BsCardHeading,
  BsPostcard,
  BsPersonFillGear,
  BsPersonCircle,
  BsBoxArrowRight,
  BsPencil,
  BsSave,
  BsPersonFill,
  BsTable,
  BsCaretLeftFill,
  BsJournalText,
  BsGeoAlt,
  BsAward,
  BsBank,
  BsLock,
  BsKey,
  BsFillCloudDownloadFill,
  BsArrowCounterclockwise,
  BsFileEarmarkArrowUp,
  BsCloudPlus,
  BsFileEarmarkPdf,
  BsPhoneVibrate,
  BsInfoCircle,
  BsCheckCircleFill,
  BsPiggyBank,
  BsCashStack,
  BsBook,
  BsGift,
  BsHeartPulse,
  BsCarFront,
  BsJournalRichtext,
  BsJournalBookmark,
  BsReceiptCutoff,
  BsFileEarmarkPlus,
  BsEnvelopeExclamation,
  BsEnvelopePlus,
  BsEnvelopeCheck,
  BsRepeat,
  BsFileEarmarkRuled,
  BsCardList,
  BsCalendar3,
  BsFileEarmarkCheck,
  BsFileEarmarkArrowDown,
  BsFileEarmarkBarGraph,
  BsPatchExclamation,
  BsPieChart,
  BsFileEarmarkText,
  BsFileEarmarkRichtext,
  BsMortarboard,
  BsDisplay,
  BsPrescription2,
  BsGrid3X3Gap,
  BsHandIndex,
  BsPhone,
  BsArrowUp,
  BsChevronDoubleLeft,
} from 'react-icons/bs';

const IconLibrary: { [key: string]: JSX.Element } = {
  phone: <BsPhone />,
  rightArrow: <BsChevronRight />,
  downArrow: <BsArrowDownCircle />,
  search: <BsSearch />,
  bell: <BsBell />,
  cross: <BsX />,
  facebook: <BsFacebook />,
  twitter: <BsTwitter />,
  youtube: <BsYoutube />,
  instagram: <BsInstagram />,
  linkedin: <BsLinkedin />,
  telephone: <BsTelephone />,
  important: <BsFillExclamationCircleFill />,
  chevronLeft: <BsChevronLeft />,
  chevronRight: <BsChevronRight />,
  star: <BsStar />,
  starFill: <BsStarFill />,
  person: <BsPerson />,
  back: <BsReplyFill />,
  moneyCoin: <BsCashCoin />,
  printer: <BsPrinter />,
  settings: <BsGearWideConnected />,
  happy: <BsEmojiLaughing />,
  cloud: <BsCloudDrizzle />,
  bulb: <BsLightbulb />,
  house: <BsHouseDoor />,
  list: <BsList />,
  copy: <BsFront />,
  mail: <BsEnvelope />,
  plus_dotted: <BsPlusCircleDotted />,
  images: <BsImages />,
  image_alt: <BsImageAlt />,
  chat: <BsChatRightDots />,
  event: <BsCalendarEvent />,
  calender: <BsCalendarCheck />,
  filter: <BsFilter />,
  menu: <BsMenuButtonWideFill />,
  file: <BsFileText />,
  list_check: <BsListCheck />,
  sort: <BsSortUp />,
  news: <BsNewspaper />,
  contacts: <BsPersonVideo2 />,
  link: <BsLink45Deg />,
  footer: <BsLayoutSplit />,
  doc: <BsFileEarmarkMedical />,
  download: <BsDownload />,
  check: <BsCheck />,
  eye: <BsEye />,
  doubleDown: <BsChevronDoubleDown />,
  doubleLeft: <BsChevronDoubleLeft />,
  factCard: <BsCreditCard2Front />,
  shield: <BsShieldLock />,
  fingerprint: <BsFingerprint />,
  people: <BsPeopleFill />,
  visit: <BsCardHeading />,
  post: <BsPostcard />,
  profileGear: <BsPersonFillGear />,
  profile: <BsPersonCircle />,
  boxArrow: <BsBoxArrowRight />,
  pencil: <BsPencil />,
  save: <BsSave />,
  personLogo: <BsPersonFill />,
  table: <BsTable />,
  scroll: <BsCaretLeftFill />,
  journal_text: <BsJournalText />,
  location: <BsGeoAlt />,
  award: <BsAward />,
  bank: <BsBank />,
  lock: <BsLock />,
  key: <BsKey />,
  pdfDownload: <BsFillCloudDownloadFill />,
  reset: <BsArrowCounterclockwise />,
  upload_file: <BsFileEarmarkArrowUp />,
  cloud_plus: <BsCloudPlus />,
  pdf: <BsFileEarmarkPdf />,
  up: <BsArrowUp />,
  vibration: <BsPhoneVibrate />,
  checkFill: <BsCheckCircleFill />,
  listCheck: <BsListCheck />,
  piggyBank: <BsPiggyBank />,
  cashStack: <BsCashStack />,
  book: <BsBook />,
  gift: <BsGift />,
  heartPulse: <BsHeartPulse />,
  carFront: <BsCarFront />,
  journalRichText: <BsJournalRichtext />,
  journalBookmark: <BsJournalBookmark />,
  receiptCutoff: <BsReceiptCutoff />,
  fileEarPlus: <BsFileEarmarkPlus />,
  envelopeExclamation: <BsEnvelopeExclamation />,
  envelopePlus: <BsEnvelopePlus />,
  envelopeCheck: <BsEnvelopeCheck />,
  repeat: <BsRepeat />,
  fileEarmarkRuled: <BsFileEarmarkRuled />,
  fileEarmarkCheck: <BsFileEarmarkCheck />,
  fileEarmarkArrowDown: <BsFileEarmarkArrowDown />,
  fileEarmarkBarGraph: <BsFileEarmarkBarGraph />,
  fileEarMarkArrowUp: <BsFileEarmarkArrowUp />,
  fileEarMarkText: <BsFileEarmarkText />,
  fileEarMarkRichText: <BsFileEarmarkRichtext />,
  cardList: <BsCardList />,
  calender3: <BsCalendar3 />,
  patchExclamation: <BsPatchExclamation />,
  pieChart: <BsPieChart />,
  mortarboard: <BsMortarboard />,
  display: <BsDisplay />,
  prescription: <BsPrescription2 />,
  grid: <BsGrid3X3Gap />,
  hand: <BsHandIndex />,
  tourIcon: <BsInfoCircle />,
};
const sortedKeys = Object.keys(IconLibrary).sort();

const Icons = sortedKeys.reduce((acc: any, key: any) => {
  acc[key] = IconLibrary[key];
  return acc;
}, {});
export default Icons;
